<?php

namespace AppBundle\Repository;

/**
 * CallAvailabilityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CallAvailabilityRepository extends \Doctrine\ORM\EntityRepository
{
}
