<?php

namespace AppBundle\Repository;

/**
 * HeatSystemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HeatSystemRepository extends \Doctrine\ORM\EntityRepository
{
}
