<?php

namespace AppBundle\Repository;

/**
 * LandingPageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LandingPageRepository extends \Doctrine\ORM\EntityRepository
{
}
