<?php

namespace AppBundle\Repository;

/**
 * LoftTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoftTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
