<?php

namespace AppBundle\Repository;

/**
 * ResourceLimitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResourceLimitRepository extends \Doctrine\ORM\EntityRepository
{
}
