app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_user_security_login:
    path: /login/
    defaults: { _controller: FOSUserBundle:Security:login }
fos_user_security_logout:
    path: /admin/logout/
    defaults: { _controller: FOSUserBundle:Security:logout }

#admin_area:
#    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
#    prefix: /admin
#
#_sonata_admin:
#    resource: .
#    type: sonata_admin
#    prefix: /admin